# Generated by Django 3.0.8 on 2020-08-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='transaction_id_user',
        ),
    ]
