# Generated by Django 3.0.8 on 2020-08-30 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitems_transaction_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
