# Generated by Django 3.0.8 on 2020-08-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitems_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
