# Generated by Django 3.0.8 on 2020-08-15 16:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('warranty_time_in_months', models.IntegerField(default=0)),
                ('manufacturing_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 16, 56, 8, 960070))),
                ('manufacturing_company', models.CharField(max_length=1000, null=True)),
                ('company_contact_number', models.CharField(max_length=12)),
                ('company_email', models.EmailField(max_length=50)),
                ('price', models.FloatField()),
                ('total_numberof_products', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id_user', models.IntegerField(default=0)),
                ('product_ordered', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id_order', models.IntegerField(default=0)),
                ('product_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
