# Generated by Django 3.0.8 on 2020-08-17 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200817_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_numberof_products',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 14, 16, 52, 21867)),
        ),
    ]
